window.TKAContractSamples = [
  {
    "id": "adriano-gomes",
    "fileName": "ADRIANO GOMES.pdf",
    "employeeName": "ADRIANO GOMES DA SILVA",
    "role": "VIGILANTE",
    "companyName": "TKA SEGURANCA PRIVADA LTDA",
    "companyCnpj": "47.711.058/0001-07",
    "cpf": "097.949.737-00",
    "city": "PINDAMONHANGABA",
    "state": "SP",
    "admissionDate": "10/04/2026",
    "contractEndDate": "24/05/2026",
    "extensionEndDate": "08/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-1.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-2.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-3.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-4.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-5.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-6.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-7.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-8.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-9.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-1.png"
  },
  {
    "id": "adriano-gomes-teste",
    "fileName": "ADRIANO GOMES TESTE.pdf",
    "employeeName": "ADRIANO GOMES DA SILVA TESTE",
    "role": "VIGILANTE",
    "companyName": "TKA SEGURANCA PRIVADA LTDA",
    "companyCnpj": "47.711.058/0001-07",
    "cpf": "097.949.737-00",
    "city": "PINDAMONHANGABA",
    "state": "SP",
    "admissionDate": "10/04/2026",
    "contractEndDate": "24/05/2026",
    "extensionEndDate": "08/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-1.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-2.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-3.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-4.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-5.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-6.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-7.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-8.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-9.png",
      "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/adriano-gomes/page-1.png"
  },
  {
    "id": "adriano-moreira",
    "fileName": "ADRIANO MOREIRA.pdf",
    "employeeName": "ADRIANO MOREIRA",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "372.772.138-31",
    "city": "GUARAREMA",
    "state": "SP",
    "admissionDate": "11/04/2026",
    "contractEndDate": "25/05/2026",
    "extensionEndDate": "09/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-1.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-2.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-3.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-4.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-5.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-6.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-7.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-8.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-9.png",
      "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/adriano-moreira/page-1.png"
  },
  {
    "id": "alex-sandro",
    "fileName": "ALEX SANDRO.pdf",
    "employeeName": "ALEX SANDRO PADILHA",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "377.049.928-05",
    "city": "SANTO ANDRE",
    "state": "SP",
    "admissionDate": "15/04/2026",
    "contractEndDate": "29/05/2026",
    "extensionEndDate": "13/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-1.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-2.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-3.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-4.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-5.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-6.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-7.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-8.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-9.png",
      "/recursos-humanos/contrato/assets/generated/alex-sandro/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/alex-sandro/page-1.png"
  },
  {
    "id": "edson-barbosa",
    "fileName": "EDSON BARBOSA.pdf",
    "employeeName": "EDSON MARCOS ALVES BARBOSA",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "300.990.178-06",
    "city": "JACAREI",
    "state": "SP",
    "admissionDate": "09/04/2026",
    "contractEndDate": "23/05/2026",
    "extensionEndDate": "07/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-1.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-2.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-3.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-4.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-5.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-6.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-7.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-8.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-9.png",
      "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/edson-barbosa/page-1.png"
  },
  {
    "id": "eduardo-maini",
    "fileName": "EDUARDO MAINI.pdf",
    "employeeName": "EDUARDO MAINI",
    "role": "VIGIA",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "143.982.898-95",
    "city": "GUARAREMA",
    "state": "SP",
    "admissionDate": "10/04/2026",
    "contractEndDate": "24/05/2026",
    "extensionEndDate": "08/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-1.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-2.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-3.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-4.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-5.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-6.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-7.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-8.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-9.png",
      "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/eduardo-maini/page-1.png"
  },
  {
    "id": "emerson-martins",
    "fileName": "EMERSON MARTINS.pdf",
    "employeeName": "EMERSON SANTOS MARTINS",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "452.046.508-73",
    "city": "SANTO ANDRE",
    "state": "SP",
    "admissionDate": "23/04/2026",
    "contractEndDate": "06/06/2026",
    "extensionEndDate": "21/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-1.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-2.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-3.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-4.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-5.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-6.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-7.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-8.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-9.png",
      "/recursos-humanos/contrato/assets/generated/emerson-martins/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/emerson-martins/page-1.png"
  },
  {
    "id": "guilherme-barbosa",
    "fileName": "GUILHERME BARBOSA.pdf",
    "employeeName": "GUILHERME BARBOSA DA SILVA",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "597.169.638-66",
    "city": "SANTO ANDRE",
    "state": "SP",
    "admissionDate": "15/04/2026",
    "contractEndDate": "29/05/2026",
    "extensionEndDate": "13/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-1.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-2.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-3.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-4.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-5.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-6.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-7.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-8.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-9.png",
      "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/guilherme-barbosa/page-1.png"
  },
  {
    "id": "julio-cesar",
    "fileName": "JULIO CESAR.pdf",
    "employeeName": "JULIO CESAR DE AVILA SILVA",
    "role": "CONTROLADOR DE ACESSO",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "438.111.498-14",
    "city": "SANTA ISABEL",
    "state": "SP",
    "admissionDate": "09/04/2026",
    "contractEndDate": "23/05/2026",
    "extensionEndDate": "07/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-1.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-2.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-3.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-4.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-5.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-6.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-7.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-8.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-9.png",
      "/recursos-humanos/contrato/assets/generated/julio-cesar/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/julio-cesar/page-1.png"
  },
  {
    "id": "natalia-tadeu",
    "fileName": "NATALIA TADEU.pdf",
    "employeeName": "NATALIA TADEU DA SILVA SANTOS",
    "role": "AUXILIAR DE SERVICOS GERAIS",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "362.134.258-37",
    "city": "TAUBATE",
    "state": "SP",
    "admissionDate": "23/04/2026",
    "contractEndDate": "06/06/2026",
    "extensionEndDate": "21/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-1.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-2.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-3.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-4.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-5.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-6.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-7.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-8.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-9.png",
      "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/natalia-tadeu/page-1.png"
  },
  {
    "id": "nilton-cesar",
    "fileName": "NILTON CESAR.pdf",
    "employeeName": "NILTON CESAR DE SOUZA",
    "role": "VIGIA",
    "companyName": "TKA SECURITY LTDA",
    "companyCnpj": "43.946.864/0001-03",
    "cpf": "263.933.208-26",
    "city": "SANTA ISABEL",
    "state": "SP",
    "admissionDate": "18/04/2026",
    "contractEndDate": "01/06/2026",
    "extensionEndDate": "16/07/2026",
    "pageUrls": [
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-1.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-2.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-3.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-4.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-5.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-6.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-7.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-8.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-9.png",
      "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-10.png"
    ],
    "thumbnailUrl": "/recursos-humanos/contrato/assets/generated/nilton-cesar/page-1.png"
  }
];
